In [1]:
import numpy as np
import pandas as pd

In [2]:
# split on the LA features for example
df = pd.read_csv('../data/Los_Angeles_feat.csv', index_col=['date'])

In [3]:
df

,positive,negative,neutral,non_irony,irony,non-hate,hate,non-offensive,offensive
date,,,,,,,,,
2022-01-01,0.46,0.15,0.39,0.78,0.22,1.00,0.00,0.90,0.10
2022-01-02,0.51,0.17,0.32,0.73,0.27,0.99,0.01,0.95,0.05
2022-01-03,0.41,0.26,0.33,0.81,0.19,0.99,0.01,0.81,0.19
2022-01-04,0.34,0.31,0.35,0.83,0.17,1.00,0.00,0.91,0.09
2022-01-05,0.42,0.28,0.30,0.78,0.22,0.98,0.02,0.84,0.16
...,...,...,...,...,...,...,...,...,...
2022-12-27,0.45,0.14,0.41,0.78,0.22,0.99,0.01,0.91,0.09
2022-12-28,0.43,0.22,0.35,0.82,0.18,0.98,0.02,0.89,0.11
2022-12-29,0.29,0.29,0.42,0.75,0.25,1.00,0.00,0.82,0.18
2022-12-30,0.48,0.18,0.34,0.83,0.17,1.00,0.00,0.90,0.10
2022-12-31,0.62,0.13,0.25,0.78,0.22,0.99,0.01,0.94,0.06

In [4]:
shuffled_df = df.sample(frac=1).reset_index()
split_idx = int(0.8 * shuffled_df.shape[0])
Xtrain = shuffled_df[:split_idx]
Xtest = shuffled_df[split_idx:]

In [5]:
Xtrain

,date,positive,negative,neutral,non_irony,irony,non-hate,hate,non-offensive,offensive
0,2022-01-11,0.45,0.19,0.36,0.80,0.20,0.98,0.02,0.89,0.11
1,2022-10-21,0.51,0.17,0.32,0.82,0.18,1.00,0.00,0.95,0.05
2,2022-01-25,0.40,0.15,0.45,0.80,0.20,1.00,0.00,0.94,0.06
3,2022-01-26,0.42,0.21,0.37,0.80,0.20,0.99,0.01,0.94,0.06
4,2022-07-16,0.39,0.16,0.45,0.86,0.14,1.00,0.00,0.95,0.05
...,...,...,...,...,...,...,...,...,...,...
287,2022-04-05,0.47,0.22,0.31,0.78,0.22,0.99,0.01,0.92,0.08
288,2022-01-07,0.48,0.25,0.27,0.78,0.22,1.00,0.00,0.85,0.15
289,2022-10-02,0.45,0.26,0.29,0.73,0.27,1.00,0.00,0.90,0.10
290,2022-03-27,0.48,0.18,0.34,0.79,0.21,0.99,0.01,0.91,0.09
291,2022-07-17,0.33,0.30,0.37,0.77,0.23,1.00,0.00,0.88,0.12

In [6]:
# extract the dates in the training set and test set
train_dates = Xtrain['date']
test_dates = Xtest['date']